TEST_CASE_NAMES = [
    '配置/信息泄露 (Configuration information leakage)',
    '硬编码密码和秘钥测试 (Hard coded password and key testing)',
    '日志信息泄露 (Log information leakage)',
    '源代码泄露 (Source code leakage)',
    '敏感数据返回前端 (Sensitive data returned to the front-end)',
    'SourceMap文件泄露 (SourceMap file leak)',
    '备份文件泄露 (Backup file leakage)',
    '接口文档泄露 (Interface document leakage)',
    '中间件版本信息泄露 (Middleware version information leakage)',
    'Web缓存中毒 (Web cache poisoning)',
    'Web缓存欺骗 (Web cache spoofing)',
    'CSRF（跨站请求伪造） (CSRF)',
    'URL重定向 (URL redirection)',
    'JSONP跨域劫持 (JSONP cross domain hijacking)',
    'HTTP请求走私 (HTTP request smuggling)',
    '无会话超时 (No session timeout)',
    'DOM型XSS (DOM type XSS)',
    '覆盖注册 (Coverage registration)',
    '任意文件读取 (Read any file)',
    'host头攻击 (Host Head Attack)',
    '交易流程绕过 (Transaction process bypass)',
    '存储型XSS (Storage XSS)',
    '文件包含 (The file contains)',
    '重放漏洞 (Replay vulnerability)',
    '任意文件下载 (Download any file)',
    '交易负值反冲 (Negative value reversal in trading)',
    '交易篡改商品属性 (Trading tampering with product attributes)',
    '交易0元购 (Transaction 0 yuan purchase)',
    '短信/邮件炸弹及恶意消耗短信资源测试',
    'Cookie不安全参数引用 (Cookie unsafe parameter reference)',
    '重要数据存储保密性保护措施缺失',
    '重要数据传输完整性保护措施缺失',
    'Cookie参数污染 (Cookie parameter pollution)',
    'CORS跨域资源共享 (CORS)',
    '短信/邮件验证码可爆破',
    '密码可爆破 (Password can be detonated)',
    '实人认证功能可绕过',
    '密码喷洒攻击 (Password spraying attack)',
    '实名认证功能可绕过',
    '登录功能绕过测试 (Login function bypass test)',
    '是否存在强制修改初始密码的功能',
    'API认证可绕过 (API authentication can be bypassed)',
    '空口令 (Empty/weak password)',
    '反射型XSS (Reflective XSS)',
    '忘记密码可绕过 (Forgot password can be bypassed)',
    '管理后台任意用户注册',
    '报错信息泄露 (Error message leakage)',
    'BOM信息泄露（包含内网IP，数据库等）',
    '后台地址泄露 (Backend address leakage)',
    '敏感目录泄露 (Sensitive directory leakage)',
    '反序列化漏洞 (Deserialization vulnerability)',
    'LDAP注入 (LDAP Injection)',
    '目录穿越 (Directory traversal)',
    'SSTI注入 (SSTI injection)',
    'CRLF注入 (CRLF Injection)',
    'XML注入 (XML injection)',
    'XPATH注入 (XPATH injection)',
    'SSRF（服务端请求伪造） (SSRF)',
    '命令注入 (Command injection)',
    '不安全的HTTP方法 (Unsafe HTTP methods)',
    '数字水印安全性 (Security of Digital Watermarks)',
    '会话凭证敏感信息测试',
    '会话保护测试 (Session protection test)',
    '会话固定 (Fixed conversation)',
    'WEB应用黑盒扫描测试',
    '未授权测试 (Unauthorized testing)',
    '垂直越权测试 (Vertical Privilege Escalation Testing)',
    '水平越权测试 (Horizontal Privilege Escalation Testing)',
    '任意文件上传漏洞 (Arbitrary File Upload Vulnerability)',
    'SQL注入 (SQL Injection)',
    '多设备登录测试 (Multi-device login test)',
    '注销功能测试 (Logout functionality test)',
    '会话标识符更新测试',
    '密码复杂度策略',
    '人机识别验证码绕过测试',
    '用户名枚举风险 (Username Enumeration Risk)',
    '鉴别数据明文传输',
    '密码输入遮掩测试 (Password Input Masking Testing)'
]